#app
server:
  port: 8080

#spring
spring:
  devtools:
    restart:
      enabled: false

  # H2 DATABASE CONFIG
  #  datasource:
  #    type: com.zaxxer.hikari.HikariDataSource
  #    schema: classpath:/db/schema-h2.sql
  #    data: classpath:/db/data-h2.sql
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password: sa
  #    platform: h2
  #    initialization-mode: always
  #    continue-on-error: true
  #  h2:
  #    console:
  #      enabled: true
  #      path: /console

  # jdbc_config   datasource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zuber_log?characterEncoding=utf8
    username: root
    password: 123456
  # Hikari will use the above plus the following to setup connection pooling
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
#      connection-test-query: SELECT 1


#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: im.zuber.server.entity
  #  typeEnumsPackage: im.zuber.server.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    use-generated-keys: true
#logging
#logging:
#  level: warn
